permalink: /:categories/:title
pygments: true
comments: true
author:
     name: Alaattin Usta
     email: alaattin.usta@bil.omu.edu.tr
     github: austa
     facebook: alaattin.usta.94
     googleplus: 113334165445363616773
server: true
auto: true
