permalink: /:categories/:title
pygments: true
comments: true
author:
     name: Mehmet Başal
     email: mhmtbsl@ce.omu.edu.tr
     github: mhmt
     facebook: mhmtbsl53
     googleplus: 110509893554582727134
server: true
auto: true
